name: Schedule team meetings
on:
  issues:
    types: [labeled, unlabeled]
  schedule:
    - cron: 00 13 * *  2
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: pkgjs/meet@v0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        schedules: ${now/P7D}
        issueTitle: Meeting <%= date.toFormat('yyyy-MM-dd') %>
        agendaLabel: meeting-agenda
        label: meeting
