name: Schedule team meetings
on:

  schedule:
    - cron: 22 13 * *  3
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: wesleytodd/meeting-maker@v0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        schedules: ${2023-02-15T20:30:00.0Z/P1W}
        issueTitle: "meeting: Main Heart Wednesday team meeting <%= date.toFormat('yyyy-MM-dd') %>"
        agendaLabel: meeting-agenda
        labels: meeting
        
