name: Schedule team meetings
on:

  schedule:
    - cron: 30 12 * *  3
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: pkgjs/meet@v0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        schedules: ${now/P7D}
        issueTitle: Meeting <%= date.toFormat('yyyy-MM-dd') %>
        agendaLabel: meeting-agenda
        meetingLabels: meeting
