name: Schedule team meetings
on:
  schedule:
    - cron: '0 0 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: pkgjs/meet@v0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        schedules: 2020-04-02T17:00:00.0Z/P1D
